/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PainelIndexRouteImport } from './routes/painel.index'
import { Route as PainelCadastrosRouteImport } from './routes/painel.cadastros'
import { Route as PainelCadastroRouteImport } from './routes/painel.cadastro'
import { Route as PainelAgendamentosRouteImport } from './routes/painel.agendamentos'

const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelIndexRoute = PainelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PainelRoute,
} as any)
const PainelCadastrosRoute = PainelCadastrosRouteImport.update({
  id: '/cadastros',
  path: '/cadastros',
  getParentRoute: () => PainelRoute,
} as any)
const PainelCadastroRoute = PainelCadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => PainelRoute,
} as any)
const PainelAgendamentosRoute = PainelAgendamentosRouteImport.update({
  id: '/agendamentos',
  path: '/agendamentos',
  getParentRoute: () => PainelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/painel': typeof PainelRouteWithChildren
  '/painel/agendamentos': typeof PainelAgendamentosRoute
  '/painel/cadastro': typeof PainelCadastroRoute
  '/painel/cadastros': typeof PainelCadastrosRoute
  '/painel/': typeof PainelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/painel/agendamentos': typeof PainelAgendamentosRoute
  '/painel/cadastro': typeof PainelCadastroRoute
  '/painel/cadastros': typeof PainelCadastrosRoute
  '/painel': typeof PainelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/painel': typeof PainelRouteWithChildren
  '/painel/agendamentos': typeof PainelAgendamentosRoute
  '/painel/cadastro': typeof PainelCadastroRoute
  '/painel/cadastros': typeof PainelCadastrosRoute
  '/painel/': typeof PainelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/painel'
    | '/painel/agendamentos'
    | '/painel/cadastro'
    | '/painel/cadastros'
    | '/painel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/painel/agendamentos'
    | '/painel/cadastro'
    | '/painel/cadastros'
    | '/painel'
  id:
    | '__root__'
    | '/'
    | '/painel'
    | '/painel/agendamentos'
    | '/painel/cadastro'
    | '/painel/cadastros'
    | '/painel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PainelRoute: typeof PainelRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/': {
      id: '/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof PainelIndexRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/cadastros': {
      id: '/painel/cadastros'
      path: '/cadastros'
      fullPath: '/painel/cadastros'
      preLoaderRoute: typeof PainelCadastrosRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/cadastro': {
      id: '/painel/cadastro'
      path: '/cadastro'
      fullPath: '/painel/cadastro'
      preLoaderRoute: typeof PainelCadastroRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/agendamentos': {
      id: '/painel/agendamentos'
      path: '/agendamentos'
      fullPath: '/painel/agendamentos'
      preLoaderRoute: typeof PainelAgendamentosRouteImport
      parentRoute: typeof PainelRoute
    }
  }
}

interface PainelRouteChildren {
  PainelAgendamentosRoute: typeof PainelAgendamentosRoute
  PainelCadastroRoute: typeof PainelCadastroRoute
  PainelCadastrosRoute: typeof PainelCadastrosRoute
  PainelIndexRoute: typeof PainelIndexRoute
}

const PainelRouteChildren: PainelRouteChildren = {
  PainelAgendamentosRoute: PainelAgendamentosRoute,
  PainelCadastroRoute: PainelCadastroRoute,
  PainelCadastrosRoute: PainelCadastrosRoute,
  PainelIndexRoute: PainelIndexRoute,
}

const PainelRouteWithChildren =
  PainelRoute._addFileChildren(PainelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PainelRoute: PainelRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
